### ISSUE TITLE
Support language alias

### ISSUE THREAD

**Issue by alexandernst** [awgn/cgrep#15]
While `--lang=Html` works just fine, `--lang=HTML` halts with a parse error. I do understand why does this happens, I think that language args should be case insensitive and maybe even have some alias (`cpp -> c++`)

**Comment by alexandernst** [comment]
Why did this get closed? Is still applies to current verison, even if the original bug report is from 2014.

**Comment by awgn** [comment]
This ticket is closed because it's not a bug (Lang is currently parsed as command line option by means of Read typelcass). Fell free to improve the parser if you consider it worthwhile -- I'll be glad to merge your update. Thanks
