### ISSUE TITLE
If the file does not exist, cgrep should comment

### ISSUE THREAD

**Issue by srenatus** [awgn/cgrep#23]
Hi Nicola,

cgrep's behaviour if the file(s) to search in do not exist seems irritating, compared to grep:

```console
$ grep foo bar; echo $?
grep: bar: No such file or directory
2
$ cgrep foo bar # reads from stdin
^C
$ touch baz; cgrep foo bar baz; echo $?  # with an existing file, does just use this file
0
$
```

I can see that there's some logic to it, but a warning on stderr (e.g. [here](https://github.com/awgn/cgrep/blob/8469deca6f75126e28f122ff68885d65971c0842/src/Main.hs#L187)) might be a middle ground? ;)

Best
Stephan

**Comment by awgn** [comment]
There's no logic in this... It's just anther bug or regression.

A new fix is on the way... :-)


On Wed, Jul 1, 2015 at 11:19 AM, Stephan Renatus <notifications@github.com>
wrote:

> Hi Nicola,
>
> cgrep's behaviour if the file(s) to search in do not exist seems
> irritating, compared to grep:
>
> $ grep foo bar; echo $?grep: bar: No such file or directory2
> $ cgrep foo bar # reads from stdin^C
> $ touch baz; cgrep foo bar baz; echo $?  # with an existing file, does just use this file0
> $
>
> I can see that there's some logic to it, but a warning on stderr (e.g.
> here
> <https://github.com/awgn/cgrep/blob/8469deca6f75126e28f122ff68885d65971c0842/src/Main.hs#L187>
> might be a middle ground? ;)
>
> Best
> Stephan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awgn/cgrep/issues/23>.
>



-- 
The difference between theory and practice is bigger in practice than in
theory.
