### ISSUE TITLE
PCRE regexps support

### ISSUE THREAD

**Issue by lyokha** [awgn/cgrep#25]
Hi! What about PCRE regexps as most ubiquitous type? They could be used in parallel with POSIX regexps and be chosen in run-time using extra options.

**Comment by awgn** [comment]
Hi Alexey,

Currently I'm busy with other projects... Fell free to fork and add your
own implementation.

I'll be glad to merge it :-)

Thanks,
N.



On Mon, Oct 26, 2015 at 1:59 PM, Alexey Radkov <notifications@github.com>
wrote:

> Hi! What about PCRE regexps as most ubiquitous type? They could be used in
> parallel with POSIX regexps and be chosen in run-time using extra options.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awgn/cgrep/issues/25>.
>



-- 
The difference between theory and practice is bigger in practice than in
theory.

**Comment by awgn** [comment]
You are absolutely right! I'll write a short tutorial ASAP!

Thanks,
N.
